### PR TITLE
Converted indentation to 2 character width spaces

### PR DESCRIPTION
**Pull request by karltanjuan**

### CODE REVIEW

**Comment by michaelsavchuk** [comment]
Thanks! Mind telling me how you did it?

**Comment by karltanjuan** [comment]
I used online converter that makes it possible at ease :)

**Comment by karltanjuan** [comment]
You're welcome!

**Comment by karltanjuan** [comment]
Hope this will help you in the future: http://tabstospaces.com/

Enjoy!

**Pull request merged**
